package model.entity.general;

public enum EnumPassif {
	
	REPARATION_PLUS_EFFICACE,
	MORALE_AMELIORE,
	CHANCE_DE_TOUCHER_AMELIOREE,
	EQUIPE_D_ABORDAGE_SUPPLEMENTAIRE,
	AUGMENTATION_DE_LA_CAPACITE_DE_FLOTTE,
	VITESSE_DE_LA_FLOTTE,
	ATTAQUE_DE_LA_FLOTTE,
	DEFENSE_DE_LA_FLOTTE,
	SANTE_DE_LA_FLOTTE,
	BOUCLIER_DE_LA_FLOTTE,
	ESQUIVE_DE_LA_FLOTTE,
	DEFENSE_DE_PROXIMITE_AMELIOREE; 
}